export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOK_WITH_REVIEWER = 'GET_BOOK_WITH_REVIEWER';
export const CLEAR_BOOK_WITH_REVIEWER = 'CLEAR_BOOK_WITH_REVIEWER';
export const USER_LOGIN = 'USER_LOGIN';
